// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjhcVuriGsD7elj3X8v5TpKwgFaPnvHA0',
    appId: '1:336446292217:web:341a4e298b5a676ad2e228',
    messagingSenderId: '336446292217',
    projectId: 'social-media-app-2a748',
    authDomain: 'social-media-app-2a748.firebaseapp.com',
    storageBucket: 'social-media-app-2a748.appspot.com',
    measurementId: 'G-WD281V6VEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARXB3ZC6nQmLv_idDha3NFMxMe7C6nbHM',
    appId: '1:336446292217:android:17618e426ff489d3d2e228',
    messagingSenderId: '336446292217',
    projectId: 'social-media-app-2a748',
    storageBucket: 'social-media-app-2a748.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxawXHldC9ZO3IcPSE1jUK3j30I91XQtE',
    appId: '1:336446292217:ios:1f18701613a869d0d2e228',
    messagingSenderId: '336446292217',
    projectId: 'social-media-app-2a748',
    storageBucket: 'social-media-app-2a748.appspot.com',
    iosBundleId: 'com.example.mobileDevProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxawXHldC9ZO3IcPSE1jUK3j30I91XQtE',
    appId: '1:336446292217:ios:3c1500c2090fcaf9d2e228',
    messagingSenderId: '336446292217',
    projectId: 'social-media-app-2a748',
    storageBucket: 'social-media-app-2a748.appspot.com',
    iosBundleId: 'com.example.mobileDevProject.RunnerTests',
  );
}
